Fix issue #786. Delete MMDialog and MMFrame.
micro-manager/micro-manager pull request #1008
Opened 2020-11-16 21:43 UTC by zhangxiaosa

Delete MMDialog and MMFrame from all involved files except MosaicSequenceFrame and CRISPFrame, because they can't be tested if devices are not available.

2020-11-18 00:53 UTC, marktsuchida commented
I'll make sure to review this tomorrow.

2020-11-18 18:29 UTC, marktsuchida requested changes
Great start! I looked through all the changes and added comments. Quite a few are about style (not using `super.` when unnecessary and preferring `setBounds` over separate calls to `setLocation` and `setSize`), but there are two important categories of real issues:

- The `setUpBoundsMemory` and `setUpLocationMemory` methods are supposed to be called once per window, before it is displayed. They should set up everything necessary so that the window bounds or location is automatically saved. So any code that calls these methods upon specific events (such as the window closing or moving) is incorrect. If you find that such calls are necessary, it probably means that `WindowPositioning` needs to be improved to catch some edge case.

- Make sure that the correct choice is made between `setUpBoundsMemory` (for user-resizable windows) and `setUpLocationMemory` (for fixed-size windows). Usually these should correspond with the 4-parameter and 2-parameter versions of `loadAndRestorePosition`, but it is more important to match the actual type of the window. I tried to add comments for most of these, but may have missed some.

2020-11-18 18:29 UTC, marktsuchida commented on libraries/Projector/src/main/java/org/micromanager/projector/internal/ProjectorControlForm.java
> +      super.setLocation(500, 300);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/alerts/internal/AlertsWindow.java
> +      super.setLocation(300, 100);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
> +         frame.setSize(480, 320);
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
> +      super.setSize(644, 220);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
>     public void resetPosition() {
This method is only called from the constructor, so better to eliminate it and move the 2 lines to the constructor. This is also because the name `resetPosition` is misleading and in any case should not be a public method.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
I think this line is redundant and can be deleted, because `setUpBoundsMemory()` (called from the constructor) should have arranged the window position to be saved when necessary.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
> +      super.setSize(550, 600);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
This appears to be redundant. Can delete?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationEditor.java
> +
It's correct to remove the calls to `savePosition()`, but don't we still need the save/restore of `flags_` and `data_`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationEditor.java
> +      super.setSize(551, 562);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationListDlg.java
> +      super.setSize(365, 495);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/GroupEditor.java
> +      super.setSize(550, 600);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/OptionsDlg.java
> +      super.setLocation(100, 100);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelConfigEditor.java
> +      super.setSize(550, 600);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelPresetEditor.java
> +      super.setSize(450, 400);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/PresetEditor.java
> +      super.setSize(420, 300);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
> +      super.setLocation(FRAME_X_DEFAULT_POS, FRAME_Y_DEFAULT_POS);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/graph/GraphFrame.java
> +      super.setSize(542, 298);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/ConfigWizard.java
> +      super.setLocation(50, 100);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/DeviceSetupDlg.java
> +      super.setLocation(100, 100);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/DeviceSetupDlg.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
This line should not be needed. (If it doesn't work without this, we need to fix `WindowPositioning`.)

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/DeviceSetupDlg.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
This line should not be needed.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/PeripheralSetupDlg.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
This line should not be needed.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/PeripheralSetupDlg.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
This line should not be needed.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/pipelineinterface/PipelineFrame.java
> +      super.setLocation(200, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/pipelineinterface/ProcessExistingDataDialog.java
> +      super.setLocation(200, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/pixelcalibrator/ManualPreciseCalibrationThread.java
> +         super.setLocation(200, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/pixelcalibrator/ManualSimpleCalibrationThread.java
> +         super.setLocation(200, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/pixelcalibrator/PixelCalibratorDialog.java
> +      super.setLocation(200, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/positionlist/OffsetPositionsDialog.java
> +      this.setSize(320, 300);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
> +      super.setSize(362, 595);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/positionlist/TileCreatorDlg.java
> +      super.setLocation(300, 300);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/script/ScriptPanel.java
> +      super.setSize(550, 495);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/script/ScriptPanel.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
This line should not be needed.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/utils/AutofocusPropertyEditor.java
> +      super.setSize(400, 300);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/utils/HotKeysDialog.java
> +        super.setSize(377, 378);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/ASIdiSPIM/src/main/java/org/micromanager/asidispim/ASIdiSPIMFrame.java
> +      // save tab location in prefs (dialog location now handled by JDialog)
The dialog location is not handled by `JDialog`, but by `SPIMFrame`.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/ASIdiSPIM/src/main/java/org/micromanager/asidispim/utils/SPIMFrame.java
> +    * TODO: this code is duplicated between here and MMDialog(MMDialog has been replaced by JDialog).
I would leave alone this comment, because this _functionality_ is not "replaced by JDialog".

2020-11-18 18:29 UTC, marktsuchida commented on plugins/Assemble/src/main/java/org/micromanager/assembledata/AssembleDataForm.java
> +      super.setSize(449, 327);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/FrameCombiner/src/main/java/org/micromanager/plugins/framecombiner/FrameCombinerConfigurator.java
> +      super.setLocation(200, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
> +      super.setSize(1000, 640);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/ImageFlipper/src/main/java/org/micromanager/imageflipper/FlipperConfigurator.java
> +      super.setLocation(frameXPos_, frameYPos_);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/CVViewer.java
> +         super.setLocation(100, 100);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/MultiAndor/src/main/java/org/micromanager/multicamera/MultiCameraFrame.java
> +      super.setLocation(100, 100);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShadingMigForm.java
> +      super.setSize(375, 375);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/PTCTools/src/main/java/org/micromanager/ptctools/PtcToolsExecutor.java
>        });
This should not be necessary, because `setUpBoundsMemory()` called below should make the necessary arrangements.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/PTCTools/src/main/java/org/micromanager/ptctools/PtcToolsFrame.java
> +      super.setLocation(DEFAULT_WIN_X, DEFAULT_WIN_Y);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/PipelineSaver/src/main/java/org/micromanager/pipelinesaver/SaverConfigurator.java
> +      super.setLocation(300, 300);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/PipelineSaver/src/main/java/org/micromanager/pipelinesaver/SaverConfigurator.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/PointAndShootDialog.java
> +      super.setLocation(100, 100);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/PointAndShootDialog.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImagingFrame.java
> +      super.setLocation(DEFAULT_WIN_X, DEFAULT_WIN_Y);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImagingFrame.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/SequenceBufferMonitor/src/main/java/org/micromanager/plugins/sequencebuffermonitor/SequenceBufferMonitorFrame.java
> +      super.setLocation(200, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/ConfigFrame.java
> +      super.setLocation(600, 200);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/ConfigFrame.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/SplitView/src/main/java/org/micromanager/splitview/SplitViewFrame.java
> +      super.setLocation(DEFAULT_WIN_X, DEFAULT_WIN_Y);
No need for `super.` here.

2020-11-18 18:29 UTC, marktsuchida commented on plugins/SplitView/src/main/java/org/micromanager/splitview/SplitViewFrame.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/Tracker/src/main/java/com/imaging100x/tracker/TrackerControl.java
> +      super.setSize(412, 346);
No need for `super.` here.
Better to use single call to `setBounds()`.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationListDlg.java
> +      WindowPositioning.setUpLocationMemory(this, this.getClass(), null);
Shouldn't this be `setUpBoundsMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/ConfigDialog.java
> +      WindowPositioning.setUpLocationMemory(this, this.getClass(), null);
`setUpLocationMemory` (or should it be `setUpBoundsMemory`?) needs to be called before showing the window (often in the constructor when using a `JDialog` subclass) and never in methods that get called when the window closes.

In this case, that appears to be done in the subclasses of `ConfigDialog`, so it should not be needed here.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/GroupEditor.java
> +      WindowPositioning.setUpLocationMemory(this, this.getClass(), null);
Shouldn't this be `setUpBoundsMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelConfigEditor.java
> +      WindowPositioning.setUpLocationMemory(this, this.getClass(), null);
Shouldn't this be `setUpBoundsMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelPresetEditor.java
> +      WindowPositioning.setUpLocationMemory(this, this.getClass(), null);
Shouldn't this be `setUpBoundsMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/PresetEditor.java
> +      WindowPositioning.setUpLocationMemory(this, this.getClass(), null);
Shouldn't this be `setUpBoundsMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/ConfigWizard.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/ConfigWizard.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
This line should not be needed.

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/DeviceSetupDlg.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/hcwizard/PeripheralSetupDlg.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/internal/pipelineinterface/ProcessExistingDataDialog.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
> +      WindowPositioning.setUpLocationMemory(this, this.getClass(), null);
Shouldn't this be `setUpBoundsMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/MultiAndor/src/main/java/org/micromanager/multicamera/MultiCameraFrame.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-18 18:29 UTC, marktsuchida commented on plugins/PTCTools/src/main/java/org/micromanager/ptctools/PtcToolsFrame.java
> +      WindowPositioning.setUpBoundsMemory(this, this.getClass(), null);
Shouldn't this be `setUpLocationMemory`?

2020-11-20 16:31 UTC, nicost commented
Funny, I kind of like the liberal use of `super`.  It helps you realize very quickly where the method resides, and helps against difficult to find bugs that can be introduced by overriding the function later on.  The Netbeans code inspector often would issues warning about this that were solved by using `super`.

2020-11-20 17:16 UTC, marktsuchida commented
@nicost But there is another side: if `super.` is used everywhere where it is not needed, it obscures uses of `super.` that are genuinely needed. Also, using `super.` where it is not needed can result in difficult-to-find bugs because somebody may later override the called method and be puzzled that the override doesn't get called. Also, except for the common case of an overridden method calling its own superclass implementation, needing to bypass on override often (though not absolutely always) seems like an indication of some other problem in the overall code design.

What sort of warnings are you referring to?

2020-11-23 01:48 UTC, nicost commented
> What sort of warnings are you referring to?

Use of overrideable method in constructor.

2020-11-23 16:59 UTC, marktsuchida commented
@nicost Ah, I see. And I think it is fine to use `super.` in that specific case, if there is no other (simple enough) solution.

2020-11-23 17:31 UTC, marktsuchida commented
Now I get it: I was wrong. Because many of the uses of `super.` in this patch do in fact occur in the constructor (this makes all the difference), they should retain `super.`. Sorry @zhangxiaosa for the bad advice.

The reason `super.` is needed when calling local methods from the constructor is that further subclasses of the current class may override those methods with versions that use instance fields of the subclass, which would not be initialized yet when the constructor of the current class executes.

A possibly _slightly_ better approach is to declare the `JFrame` subclass `final` (except in the few cases where it is designed to be further subclasses), which (I think) would also avoid the "use of overridable method in constructor" warning. But that would be better to do in a separate patch, if ever, so for now keeping the `super.` is better.

A further note is that the practice of subclassing `JFrame` itself is highly questionable, no matter how common it is in example Java code; nobody in their right mind does it in more modern GUI frameworks, and some of the windows I implemented in MMStudio avoid it (and avoiding the need to call methods from the constructor is one of several reasons why). But that's another topic entirely.

2021-02-11 17:38 UTC, nanthony21 commented
One issue I see here is that all frames are now missing the Micro-Manager icon in the top left. It's  minor thing but I think having the default Java "Coffee" icon on all of the frames gives the program a kind of unfinished look.

Aside from that are there any remaining reasons not to go ahead with merging this?

2021-02-11 19:57 UTC, marktsuchida commented
@nanthony21 Thanks for pointing out about the icon; I genuinely missed that.

It turns out there is also the functionality of `MMFrame.setupMenus()`, which is actually more critical.

Let me work on this today and tomorrow; I'd also like to finish this before it accumulates more merge conflicts.

2021-02-27 19:15 UTC, closed without merging