Plugin linting, should make all (?) plugins pass Checkstyle error free.
micro-manager/micro-manager pull request #1567
Opened 2022-11-20 19:11 UTC by nicost

2022-11-20 20:25 UTC, nicost commented
I believe the only one left is the ASIdiSPIM plugin, which is actually not used (it was a botched attempt by me to port the 1.4 plugin to 2.0), so we can remove that code.

2022-11-21 14:58 UTC, marktsuchida commented on plugins/CRISP/src/main/java/com/asiimaging/crisp/UserSettings.java
> +   ;
```suggestion
```

2022-11-21 17:55 UTC, marktsuchida requested changes
Good to see most of our Java code cleaned up.

I went over most of the changes (though I'm sure my eyes were glazed over for parts of it) and did not find anything amiss except for one bug that was about to be introduced (in SnapOnMove). This is a little concerning, so I did a quick second pass with `git diff --color-moved` and caught another one (in SlideExplorer). Both of these had a variable initialization moved to a location where the value would be incorrect. However, if there were any moved variable definitions that were not a verbatim move, I would have missed them.

Can you be reasonably confident that similar bugs are not introduced elsewhere in this PR? Otherwise I should probably take another pass with an eye for this kind of issue -- or we should start over with a safer strategy.

This might be the last big batch of half-manual code style fixes, but if ever doing something like this again in the future, it would be good to try to isolate changes by category. For example, if each commit only contains changes for a particular type of style violation, it is much more feasible for a human to meaningfully review (and changes that are guaranteed not to change the meaning of code can be more easily excluded from review, drastically reducing the amount of work (which was 3.5 hours this time). See #1469 for an example of this.

Also, I could not (easily) review the changes in `com.asiimaging.asigamepad`, `org.micromanager.pmqi`, and `PGFocusFrame.java` because the files were moved in the same commit as the edits (if any). It's good to put file moves/renames in their own commit when possible (the change to the `package` statement should still go in the same commit as the move/rename so that each commit is consistent).

My suggested changes other than the 2 bugs mentioned above are all minor/nitpicks and in the following categories:
- Add/nitpick unicode codepoint comments
- Delete spurious semicolons
- File header comments shouldn't be Javadoc comments

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Emu/src/test/java/de/embl/rieslab/emu/swinglisteners/SwingUIListenersTest.java
> +      final String value = "\u00A3$\u00A3!14,:{"; // symbols?
```suggestion
      final String value = "\u00A3$\u00A3!14,:{"; // U+00A3 POUND SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/CRISP/src/main/java/com/asiimaging/crisp/UserSettings.java
> +   ;
```suggestion
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Emu/src/test/java/de/embl/rieslab/emu/swinglisteners/SwingUIListenersTest.java
> +            ;
```suggestion
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Emu/src/test/java/de/embl/rieslab/emu/ui/uiparameters/StringUIParameterTest.java
> +      String s = "2fsdj*745+$\u00A3%$6(*&) {}~'"; // not sure what sumbol this is.
```suggestion
      String s = "2fsdj*745+$\u00A3%$6(*&) {}~'"; // U+00A3 POUND SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Emu/src/test/java/de/embl/rieslab/emu/ui/uiparameters/StringUIParameterTest.java
> +      s = "\u00A3$sdjdsn"; // symbol?
```suggestion
      s = "\u00A3$sdjdsn"; // U+00A3 POUND SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Emu/src/test/java/de/embl/rieslab/emu/ui/uiparameters/UIPropertyParameterTest.java
> +      String s = "2fsdj*745+$\u00A3%$6(*&) {}~'"; // symbols
```suggestion
      String s = "2fsdj*745+$\u00A3%$6(*&) {}~'"; // U+00A3 POUND SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Emu/src/test/java/de/embl/rieslab/emu/ui/uiparameters/UIPropertyParameterTest.java
> +      s = "\u00A3$sdjdsn"; // symbols
```suggestion
      s = "\u00A3$sdjdsn"; // U+00A3 POUND SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/MainForm.java
> +   ;
```suggestion
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/ImageFlipper/src/main/java/org/micromanager/imageflipper/FlipperConfigurator.java
> +   private static final String R270 = "270" + "\u00B0"; // degree symbol
```suggestion
   private static final String R0 = "0" + "\u00B0"; // U+00B0 DEGREE SIGN
   private static final String R90 = "90" + "\u00B0"; // U+00B0 DEGREE SIGN
   private static final String R180 = "180" + "\u00B0"; // U+00B0 DEGREE SIGN
   private static final String R270 = "270" + "\u00B0"; // U+00B0 DEGREE SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisition.java
>  /**
```suggestion
/*
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisition.java
> + * <p>LICENSE:      This file is distributed under the BSD license.
```suggestion
 * LICENSE:      This file is distributed under the BSD license.
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisition.java
> + * <p>This file is distributed in the hope that it will be useful,
```suggestion
 *    This file is distributed in the hope that it will be useful,
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisition.java
> + * <p>IN NO EVENT SHALL THE COPYRIGHT OWNER OR
```suggestion
 *    IN NO EVENT SHALL THE COPYRIGHT OWNER OR
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisitionFrame.java
>  /**
```suggestion
/*
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisitionFrame.java
> + * <p>Nico Stuurman, copyright UCSF, 2012, 2015
```suggestion
 * Nico Stuurman, copyright UCSF, 2012, 2015
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisitionFrame.java
> + * <p>LICENSE:      This file is distributed under the BSD license.
```suggestion
 * LICENSE:      This file is distributed under the BSD license.
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisitionFrame.java
> + * <p>This file is distributed in the hope that it will be useful,
```suggestion
 * This file is distributed in the hope that it will be useful,
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/IntelligentAcquisition/src/main/java/org/micromanager/intelligentacquisition/IntelligentAcquisitionFrame.java
> + * <p>IN NO EVENT SHALL THE COPYRIGHT OWNER OR
```suggestion
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/MultiAndor/src/main/java/org/micromanager/multicamera/MultiCameraFrame.java
> +               tempText += core_.getProperty(camera, TEMP) + "\u00b0" + "C   "; // degree symbol
```suggestion
               tempText += core_.getProperty(camera, TEMP) + "\u00b0" + "C   "; // U+00B0 DEGREE SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/utils/ListUtils.java
>  /**
```suggestion
/*
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/utils/ListUtils.java
> + * <p>Copyright (c) 2013-2017, Regents of the University of California
```suggestion
 * Copyright (c) 2013-2017, Regents of the University of California
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/utils/ListUtils.java
> + * <p>Redistribution and use in source and binary forms, with or without
```suggestion
 * Redistribution and use in source and binary forms, with or without
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/utils/ListUtils.java
> + * <p>1. Redistributions of source code must retain the above copyright notice, this
```suggestion
 * 1. Redistributions of source code must retain the above copyright notice, this
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/utils/ListUtils.java
> + * <p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
```suggestion
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/PointAndShootAnalysis/src/main/java/org/micromanager/pointandshootanalysis/utils/ListUtils.java
> + * <p>The views and conclusions contained in the software and documentation are those
```suggestion
 * The views and conclusions contained in the software and documentation are those
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Recall/src/main/java/org/micromanager/recall/RecallPlugin.java
>  /**
```suggestion
/*
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Recall/src/main/java/org/micromanager/recall/RecallPlugin.java
> + * <p>This plugin will copy all images in the Micro-Manager circular buffer
```suggestion
 * This plugin will copy all images in the Micro-Manager circular buffer
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Recall/src/main/java/org/micromanager/recall/RecallPlugin.java
> + * <p>This is useful when you see something interesting in live mode and want to
```suggestion
 * This is useful when you see something interesting in live mode and want to
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Recall/src/main/java/org/micromanager/recall/RecallPlugin.java
> + * <p>Nico Stuurman, 2009(?)
```suggestion
 * Nico Stuurman, 2009(?)
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Recall/src/main/java/org/micromanager/recall/RecallPlugin.java
> + * <p>Updated June 2013 to use ImageProcssor Queue, so that images from multiple
```suggestion
 * Updated June 2013 to use ImageProcssor Queue, so that images from multiple
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Recall/src/main/java/org/micromanager/recall/RecallPlugin.java
> + * <p>Copyright University of California
```suggestion
 * Copyright University of California
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/Recall/src/main/java/org/micromanager/recall/RecallPlugin.java
> + * <p>LICENSE:      This file is distributed under the BSD license.
```suggestion
 * LICENSE:      This file is distributed under the BSD license.
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/MainController.java
> +      boolean wasEnabled = isEnabled();
```suggestion
      boolean wasEnabled = isEnabled();
      setEnabled(false);
      changeCriteria_.clear();
      changeCriteria_.addAll(criteria);
```

This would have introduced a bug.

2022-11-21 17:55 UTC, marktsuchida commented on plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/PlotPanel.java
> +                     "Position (\u00B5m)", // Greek mu
```suggestion
                     "Position (\u00B5m)", // U+00B5 MICRO SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
> +      spacingLabel.setText("Spacing [\u00b5m]"); // Greek mu
```suggestion
      spacingLabel.setText("Spacing [\u00b5m]"); // U+00B5 MICRO SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
> +               spacingLabel.setText("Spacing [\u00b5m]"); // Greek mu
```suggestion
               spacingLabel.setText("Spacing [\u00b5m]"); // U+00B5 MICRO SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
> +               spacingLabel.setText("Spacing X,Y [\u00b5m]"); // Greek mu
```suggestion
               spacingLabel.setText("Spacing X,Y [\u00b5m]"); // U+00B5 MICRO SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
> +               spacingLabel.setText("Overlap [\u00b5m]"); // Greek mu
```suggestion
               spacingLabel.setText("Overlap [\u00b5m]"); // U+00B5 MICRO SIGN
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/SlideExplorer/src/main/java/org/micromanager/slideexplorer/ConfigurationDialog.java
> +                "y-offset, \u03BCm", "z-offset, \u03BCm"}; // Greek mu
```suggestion
               {"Resolution setting", "x-offset, \u03BCm",  // U+03BC GREEK SMALL LETTER MU
                "y-offset, \u03BCm", "z-offset, \u03BCm"}; // U+03BC GREEK SMALL LETTER MU
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/SlideExplorer/src/main/java/org/micromanager/slideexplorer/Hub.java
> +      int originalZoomLevel = zoomLevel_;
```suggestion
```

2022-11-21 17:55 UTC, marktsuchida commented on plugins/SlideExplorer/src/main/java/org/micromanager/slideexplorer/Hub.java
>        zoomLevel_ = zoomLevel;
```suggestion
      int originalZoomLevel = zoomLevel_;
      zoomLevel_ = zoomLevel;
```

This would have introduced a bug.

2022-11-21 19:31 UTC, marktsuchida approved these changes

2022-11-21 19:39 UTC, merged

2022-11-21 19:40 UTC, marktsuchida commented
Lesson learned: don't use GitHub's "suggest change" when there are more than a few changes to suggest.

I put the changes I suggested into 4 commits and added a 5th that re-fixes Checkstyle violations.

@nicost Great if you could check my last commit (especially the zoom level change). I think I got it right but an extra pair of eyes is always good. Otherwise ready to merge.