Duplicator plugin: select any channel, and saves output
micro-manager/micro-manager pull request #1657
Opened 2023-03-13 22:48 UTC by nicost

Previously, only ranges of axes could be selected.  That proved to be cumbersome when desiring to select a sub-set of channels.  

Also added the ability to save directly to any of the formats supported by MM.

2023-03-14 18:14 UTC, marktsuchida requested changes
Just one thing.

2023-03-14 18:14 UTC, marktsuchida commented on mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/ImageJBridge.java
> +      }
This method (and pretty much everything in `ImageJBridge`) is meant to always be called on the EDT only. The bug is in the caller if this is not the case. Hence the (unenforced, for-human) annotation [`@MustCallOnEDT`](https://github.com/micro-manager/micro-manager/blob/7f331552384dcf92a53cc5f75c22ee77ef338f6c/mmstudio/src/main/java/org/micromanager/internal/utils/MustCallOnEDT.java#L19-L28) (it _must_ be called on the EDT; it doesn't automatically schedule itself on the EDT).

The idea is that Swing GUI is fundamentally single-threaded, and the larger part of our code around it that we can carve out and keep single-threaded, the simpler the overall system.

Happy to suggest alternative fixes if you can provide details on how this gets called on a non-EDT thread. At the moment, the only call to this method I can find is also from a method marked with `@MustCallOnEDT`.

2023-03-15 19:05 UTC, nicost commented on mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/ImageJBridge.java
> +      }
Good call.  I can not reproduce the issue after removing those lines.  May have been solved by other changes I made.  Removed for now.

2023-03-16 18:48 UTC, marktsuchida approved these changes

2023-03-16 19:06 UTC, merged